version: '3.8'

services:
  db:
    image: postgres:14
    container_name: my-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: test_db
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - ./db_config.sh:/app/db_config.sh
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres-network

  sandbox:
    build: .
    container_name: sandbox-container
    volumes:
      - .:/app
    working_dir: /app
    tty: true
    networks:
      - postgres-network
    depends_on:
      - db
    # Modify the command to process db_config.sh at runtime
    command: /bin/bash -c "dos2unix /app/db_config.sh && chmod +x /app/db_config.sh && /bin/bash"

volumes:
  postgres_data:

networks:
  postgres-network:
    driver: bridge

