version: '3.8'

services:
  db:
    image: postgres:14
    container_name: my-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: test_db
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres-network

  sandbox:
    build: .
    container_name: sandbox-container
    volumes:
      - .:/app
    networks:
      - postgres-network
    depends_on:
      - db

volumes:
  postgres_data:

networks:
  postgres-network:
    driver: bridge
