version: '3.8'

services:
  db:
    image: postgres:14
    container_name: my-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: test_db
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - ./db_config.sh:/app/db_config.sh
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres-network

  sandbox:
    image: alpine:latest
    container_name: sandbox-container
    volumes:
      - .:/app
    working_dir: /app
    tty: true
    networks:
      - postgres-network
    depends_on:
      - db
    command: /bin/sh -c "apk add --no-cache make bash curl git postgresql-client && echo 'y' | curl -fsSL https://git.io/shellspec | sh -s -- --yes && chmod +x /app/db_config.sh && export PATH=\$PATH:/root/.local/bin && /bin/sh"

volumes:
  postgres_data:

networks:
  postgres-network:
    driver: bridge

